const KEY="civicconnect_reports";let reports=JSON.parse(localStorage.getItem(KEY)||"[]");
const tr={en:["Report an issue. Track progress. Improve your community.","Report civic problems with location, category and seriousness so authorities can organize and prioritize action."],te:["సమస్యను నివేదించండి. పురోగతిని ట్రాక్ చేయండి. మీ సమాజాన్ని మెరుగుపరచండి.","ప్రాంతం, సమస్య రకం మరియు తీవ్రతతో పౌర సమస్యలను నివేదించండి."],hi:["समस्या रिपोर्ट करें। प्रगति ट्रैक करें। अपने समुदाय को बेहतर बनाएं.","स्थान, श्रेणी और गंभीरता के साथ नागरिक समस्याओं की रिपोर्ट करें।"]};
function save(){localStorage.setItem(KEY,JSON.stringify(reports));stats();renderDashboard()}
function stats(){totalCount.textContent=reports.length;openCount.textContent=reports.filter(x=>x.status!=="Resolved").length;resolvedCount.textContent=reports.filter(x=>x.status==="Resolved").length}
function showSection(id){document.querySelectorAll(".section").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.section===id));if(id==="dashboard")renderDashboard();scrollTo(0,0)}
language.onchange=e=>{heroTitle.textContent=tr[e.target.value][0];heroText.textContent=tr[e.target.value][1]}
function toast(s){const x=document.getElementById("toast");x.textContent=s;x.style.display="block";setTimeout(()=>x.style.display="none",2500)}
function useLocation(){if(!navigator.geolocation)return toast("Location is not supported.");navigator.geolocation.getCurrentPosition(p=>{location.value=`GPS: ${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`;toast("Location added.")},()=>toast("Location permission was not granted."))}
function readFile(f){return new Promise((ok,no)=>{let r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)})}
reportForm.onsubmit=async e=>{e.preventDefault();let f=photo.files[0],pic=f?await readFile(f):"";let id="CC-"+(1001+reports.length),now=new Date();
let r={id,title:title.value.trim(),category:category.value,location:location.value.trim(),severity:severity.value,expectedDate:expectedDate.value,contact:contact.value.trim(),description:description.value.trim(),photo:pic,status:"Submitted",timeline:[{status:"Submitted",date:now.toLocaleString(),note:"Citizen report received."}]};
reports.push(r);save();e.target.reset();formMessage.textContent=`Report submitted successfully. Your Report ID is ${id}.`;formMessage.style.color="var(--g)";trackId.value=id;toast("Thank you for reporting the issue.");showSection("track");trackReport()}
function esc(v){return String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function trackReport(){let id=trackId.value.trim().toUpperCase(),r=reports.find(x=>x.id===id);if(!r){trackResult.innerHTML="<p>No report found. Check the Report ID.</p>";return}
trackResult.innerHTML=`<div class="card"><h3>${esc(r.title)}</h3><p>${r.id} • ${esc(r.category)} • ${esc(r.location)}</p><span class="priority ${r.severity}">${r.severity} Priority</span><p>${esc(r.description)}</p>${r.photo?`<img src="${r.photo}" style="max-width:100%;max-height:280px;border-radius:10px">`:""}<div class="timeline">${r.timeline.map(t=>`<div class="timeline-item"><b>${esc(t.status)}</b><div class="small">${esc(t.date)}</div><div>${esc(t.note)}</div></div>`).join("")}</div></div>`}
function pv(s){return {Critical:4,High:3,Medium:2,Low:1}[s]||0}
function renderDashboard(){if(!reports.length){dashboardList.innerHTML="<p>No citizen reports yet.</p>";return}let a=[...reports].sort((x,y)=>pv(y.severity)-pv(x.severity));
dashboardList.innerHTML=a.map(r=>`<div class="card"><div class="head"><div><h3>${esc(r.title)}</h3><small>${r.id} • ${esc(r.category)} • ${esc(r.location)}</small></div><span class="priority ${r.severity}">${r.severity}</span></div><p>${esc(r.description)}</p><label>Status<select onchange="changeStatus('${r.id}',this.value)">${["Submitted","Under Review","Assigned","In Progress","Resolved"].map(s=>`<option ${r.status===s?"selected":""}>${s}</option>`).join("")}</select></label></div>`).join("")}
function changeStatus(id,status){let r=reports.find(x=>x.id===id);r.status=status;r.timeline.push({status,date:new Date().toLocaleString(),note:`Status updated to ${status}.`});save();toast("Status updated.")}
stats();
